# Exercise of Bag Of Words
* In this Exercise, you are going to classify whether a given movie review is positive or negative.
* You are going to use Bag of words for pre-processing the text and apply different classification algorithms.
* Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

In [3]:
#1. read the data provided in the same directory with name 'movies_sentiment_data.csv' and store it in df variable
import pandas as pd

df = pd.read_csv('movies_sentiment_data.csv')

#2. print the shape of the data
print(f"Shape of the data frame : {df.shape}")

#3. print top 5 datapoints
df.head()

Shape of the data frame : (19000, 2)

                                              review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [9]:
#Creating a new column "Category" which represent 1 if the sentiment is positive or 0 if it is negative

# Approach 1 using Lambda Function (Just another way to write like 2nd approach)
# df['Category'] = df['sentiment'].apply(lambda x: 1 if x=='positive' else 0)

# Approach 2 using map (More Controlled and Preferred) - Here we can add as many category as we want.
df['Category'] = df['sentiment'].map({
    'negative':0,
    'positive':1
})

# Approach 2 using LabelEncoder
# from sklearn.preprocessing import LabelEncoder

# encoder = LabelEncoder()
# Category = encoder.fit_transform(df.sentiment)
# df['Category'] = Category


df.head()

                                              review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [11]:
#check the distribution of 'Category' and see whether the Target labels are balanced or not.
df['Category'].value_counts()

Category
1    9500
0    9500
Name: count, dtype: int64

In [ ]:
#Do the 'train-test' splitting with test size of 20%
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df['review'],df['Category'],test_size=0.2)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(15200,)
(15200,)
(3800,)
(3800,)

Exercise-1

using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.

Note:

use CountVectorizer for pre-processing the text.

use Random Forest as the classifier with estimators as 50 and criterion as entropy.

print the classification report.


References:

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

classifier = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('RandomForestClassifier',RandomForestClassifier(n_estimators=50,criterion='entropy'))
])

classifier.fit(X_train,y_train)

y_pred_clf = classifier.predict(X_test)
print(classification_report(y_test,y_pred_clf))

              precision    recall  f1-score   support

           0       0.84      0.83      0.84      1938
           1       0.83      0.84      0.83      1862

    accuracy                           0.84      3800
   macro avg       0.84      0.84      0.84      3800
weighted avg       0.84      0.84      0.84      3800

* Our RandomForestClassifier Model is giving us 84% Accuracy.

# How to read this report and what each component is telling
* Precision: Out of everything |the model predicted as positive, how much was actually positive?
* Recall: Out of everything that was actually positive, how much did the model successfully find?
* F1-score: Combination of Precision + Recall (using their harmonic mean). If both precision and recall are good, F1 will also be good.

F1 = 2 × (Precision × Recall)  /  (Precision + Recall)

* Support → Number of actual examples - How many actual samples belong to each class

Exercise-2

* using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

Note:

* use CountVectorizer for pre-processing the text.
* use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean'.
* print the classification report.

References:

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('knn',KNeighborsClassifier(n_neighbors=10,metric='euclidean'))
])

knn_clf.fit(X_train,y_train)

y_pred_knn_clf = knn_clf.predict(X_test)
print(classification_report(y_test,y_pred_knn_clf))

              precision    recall  f1-score   support

           0       0.65      0.65      0.65      1938
           1       0.64      0.63      0.64      1862

    accuracy                           0.64      3800
   macro avg       0.64      0.64      0.64      3800
weighted avg       0.64      0.64      0.64      3800

Hmmm..here the performance of various metrics (precision, recall etc.) seem to be lower (~60 %). Let's try one more classifier and then discuss why performance is varying so much

Exercise-3

* using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..

Note:

* use CountVectorizer for pre-processing the text.
* use Multinomial Naive Bayes as the classifier.
* print the classification report.

References:

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

In [27]:
from sklearn.naive_bayes import MultinomialNB
nb_clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

nb_clf.fit(X_train,y_train)

y_pred_nb_clf= nb_clf.predict(X_test)
print(classification_report(y_test,y_pred_nb_clf))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1938
           1       0.86      0.81      0.83      1862

    accuracy                           0.84      3800
   macro avg       0.84      0.84      0.84      3800
weighted avg       0.84      0.84      0.84      3800

# Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB ?

KNN = "Find similar examples."
* High-dimensional text (bcz of BoW) → calculating distances becomes difficult → may perform poorly.

Multinomial Naive Bayes = "Which words are likely for each class?"
* Works naturally with word counts/frequencies → often useful for text classification.

Random Forest = "Many decision trees vote together."
* Uses different samples/features → can handle many features and capture useful patterns.

Final point
* Don't assume an algorithm will work best. Try suitable algorithms, evaluate them using metrics like F1/accuracy/precision/recall and practical requirements, then choose based on the evidence.

In [ ]:
# Testing on self Example
review_list = ["Hey That movie is very fantastic and super fabulous","I don't like the movie and the story was very boring and casual"]\

predicted_result = nb_clf.predict(review_list)
print(predicted_result) # The result [1 0] shows that our model predicted the first review as +ve and the other one as -ve.

[1 0]