# STOP words Tutorial

In [4]:
import spacy 
from spacy.lang.en.stop_words import STOP_WORDS

print(len(STOP_WORDS))
print(STOP_WORDS)

326
{'there', 'bottom', 'many', 'fifty', 'more', 'two', 'well', 'ours', 'three', 'hers', 'its', 'no', 'wherein', 'so', 'nevertheless', 'since', 'whereas', 'every', 'they', 'do', 'has', 'because', 'few', 'in', 'get', 'always', 'various', 'also', 'either', 'under', 'where', 'only', 'twelve', 'with', 'my', '‘s', 'whose', 'was', 'may', 'elsewhere', 'those', 'nowhere', 'everywhere', 'that', 'else', 'to', 'otherwise', 'ever', 'onto', 'beyond', 'then', 'while', 'somehow', 'very', 'us', '‘ve', 'name', 'cannot', 'give', 'beside', 'could', 'until', 'your', 'some', 'eight', 'been', 'here', 'whither', 'does', 'this', "'ve", 'become', 'yourselves', 'perhaps', 'latter', 'all', 'whoever', 'least', 'off', 'becoming', 'together', 'after', 'must', 'during', '‘re', 'everything', 'me', 'top', 'empty', 'our', 'afterwards', 'side', 'again', 'who', 'seemed', 'go', 'throughout', 'everyone', 'others', 'hence', 'full', 'moreover', 'mostly', 'now', 'a', 'you', 'quite', 'several', 'himself', 'rather', 'really', 'nine', 'will', 'almost', 'although', 'sometime', 'take', 'somewhere', 'toward', 'thereby', 'but', 'her', 'along', 'done', 'none', 'twenty', 'being', 'it', 'neither', 'myself', 'therefore', 'than', 'him', "'re", 'yourself', 'due', 'once', 'thereupon', 'same', 'much', 'thru', 'behind', 'whether', 'anyhow', 'often', 'did', 'over', '’s', 'just', 'had', 'fifteen', 'eleven', '‘d', 'mine', 'already', 'their', 'indeed', 'up', 'amongst', 'among', 'third', 'against', 'without', '‘m', 'ten', 'per', 'can', 'even', 're', '‘ll', 'are', 'am', 'how', 'four', 'therein', '’ll', 'thereafter', 'five', 'namely', 'within', 'still', 'other', 'further', 'through', 'she', 'becomes', 'whatever', 'see', 'we', 'put', 'below', 'he', 'whenever', "'ll", 'when', 'hundred', 'by', 'whereafter', 'move', 'upon', 'via', 'used', 'ourselves', 'show', 'as', 'before', 'anyone', 'the', 'most', 'whole', 'forty', 'his', 'might', 'down', 'across', 'whom', 'i', 'an', "'s", 'became', "'m", 'hereby', 'why', 'yours', 'towards', 'have', 'above', 'which', 'n‘t', 'anyway', 'another', 'were', 'back', 'herself', 'seems', 'into', 'six', 'seeming', 'call', 'nobody', 'keep', 'thus', 'seem', 'of', 'thence', 'wherever', 'one', "n't", 'amount', 'meanwhile', 'latterly', 'regarding', 'what', '’d', 'make', '’re', 'own', 'part', 'nothing', 'not', 'first', 'themselves', 'nor', 'yet', 'doing', 'front', 'if', "'d", 'last', 'next', 'them', 'each', 'however', 'and', 'sometimes', 'be', 'except', 'about', 'beforehand', 'serious', 'sixty', 'whereby', 'anything', 'for', 'formerly', 'ca', 'unless', 'made', 'besides', 'would', 'or', 'n’t', 'around', 'hereupon', 'at', 'is', 'noone', 'anywhere', 'please', 'herein', 'less', 'say', 'alone', 'whereupon', 'should', 'enough', 'both', 'using', 'something', 'from', 'on', 'between', 'though', 'itself', 'out', 'someone', 'hereafter', 'any', 'too', 'whence', 'former', '’ve', 'such', 'never', 'these', '’m'}

In [5]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("We just opened our wings,the flying part is coming soon")

for token in doc:
    if token.is_stop:
        print(token)

We
just
our
the
part
is

In [34]:
# Common Practice in NLP applications is to make a seperate function to Preprocess (stop_words, stemming, lemmatizaton, etc)
def preprocess(text):
    doc= nlp(text)

    # Using list comprehension
    no_stop_words_list = [token.text for token in doc if not token.is_stop and not token.is_punct]
    return " ".join(no_stop_words_list)

# print(preprocess("We just opened our wings,the flying part is coming soon"))

In [35]:
import pandas as pd

df = pd.read_json('doj_press.json',lines=True)

df.shape

(13087, 6)

In [36]:
df.head()

,id,title,contents,date,topics,components
0,NaN,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [37]:
# As we can see that many topics are of Empty List type. Let firstly take discard them
df = df[ df['topics'].str.len() != 0 ]

df.head()

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [38]:
df.shape

(4688, 6)

In [39]:
# Now lets take first 100 rows only to done our work of STOP_WORDS
df = df.head(100)

In [40]:
df.shape

(100, 6)

In [41]:
# Now we let's try to remove the stop words from the column named 'contents'
len(df['contents'].iloc[4]) # iloc is used to get the row from its integer index (like currently it will give 5th row) of the pandas dataframe

5504

In [42]:
(df['contents'].iloc[4])

'21st Century Oncology Inc. and certain of its subsidiaries and affiliates have agreed to pay $26 million to the government to resolve a self-disclosure relating to the submission of false attestations regarding the company’s use of electronic health records software and separate allegations that they violated the False Claims Act by submitting, or causing the submission of, claims for certain services provided pursuant to referrals from physicians with whom they had improper financial relationships. \xa0 “The Justice Department is committed to zealously investigating improper financial relationships that have the potential to compromise physicians’ medical judgment,” said Acting Assistant Attorney General Chad A. Readler of the Justice Department’s Civil Division.\xa0 “However, we will work with companies that accept responsibility for their past compliance failures and promptly take corrective action.”  \xa0 21st Century Oncology, which is headquartered in Fort Myers, Florida, owns and operates subsidiaries and affiliates throughout the United States that provide integrated cancer care.\xa0 As part of its business, 21st Century Oncology’s subsidiaries and affiliates employ physicians in specialty fields such as radiation oncology, medical oncology, and urology.\xa0  \xa0 The settlement announced today resolves conduct that was self-disclosed by the company regarding payments made by the government as part of the Medicare Electronic Health Records (EHR) Incentive Program.\xa0 Under the Medicare EHR Incentive Program, physicians who attest to their meaningful use of certified EHR technology may receive incentive payments and avoid downward adjustments to certain Medicare claims.\xa0 As part of its self-disclosure, 21st Century Oncology reported that it knowingly submitted, or caused the submission of, false attestations to CMS concerning employed physicians’ use of EHR software.\xa0 The company further reported that, in support of the attestations, its employees falsified data regarding the company’s use of EHR software, fabricated software utilization reports, and superimposed EHR vendor logos onto the reports to make them look legitimate.\xa0  \xa0 “This settlement represents our office’s continued commitment to ensuring compliance with important federal health care laws,” said Acting U.S. Attorney Stephen Muldrow of the Middle District of Florida.\xa0 “We appreciate that 21st Century Oncology self-reported a major fraud affecting Medicare, and we are also pleased that the company has agreed to accept financial responsibility for past compliance failures.” \xa0 The settlement also resolves the government’s allegations regarding violations of the physician self-referral law (commonly referred to as the “Stark Law.”)\xa0 The Stark Law prohibits an entity from submitting claims to Medicare for designated health services performed pursuant to referrals from physicians with whom the entity has a financial relationship unless certain designated exceptions apply.\xa0 The government alleged that 21st Century Oncology and certain of its subsidiaries and affiliates violated the FCA by submitting, or causing the submission of, claims for services performed pursuant to referrals from physicians whose compensation did not satisfy any exception to the Stark Law. \xa0 The Stark Law allegations were originally brought in a lawsuit filed by Matthew Moore, 21st Century Oncology’s former Interim Vice President of Financial Planning, under the qui tam provisions of the False Claims Act.\xa0 Under the Act, private parties may bring suit on behalf of the government and share in any recovery.\xa0 Mr. Moore will receive $2,000,000 as his share of the recovery associated with the Stark Law allegations. \xa0 In addition to the civil settlement, 21st Century Oncology has entered into a new five-year Corporate Integrity Agreement with the Office of Inspector General of the United States Department of Health and Human Services (HHS-OIG), which obligates 21st Century Oncology to undertake substantial internal compliance reforms, including hiring independent review organizations to conduct annual claims and arrangements reviews.\xa0 \xa0 “21st Century Oncology admitted to causing violation of the meaningful use regulations in order to fund an electronic health records system, as well as falsifying records to cover up those actions,” said Shimon R. Richmond, Special Agent in Charge for the Office of Inspector General of the U.S. Department of Health and Human Services.\xa0 “Separately, the government alleged that same company, through its affiliates and subsidiaries, caused certain physicians to enter into illegal financial arrangements.\xa0 Providers engaging in similar behavior should expect attention from OIG.”\xa0\xa0\xa0 \xa0 The government’s resolution of this matter illustrates the government’s emphasis on combating health care fraud.\xa0 Tips and complaints from all sources about potential fraud, waste, abuse, and mismanagement can be reported to the Department of Health and Human Services at 900-HHS-TIPS (800-447-8477). \xa0 The investigation was handled by the Civil Division’s Commercial Litigation Branch and the Fort Myers Division of\xa0the U.S. Attorney’s Office for the Middle District of Florida, with assistance from the U.S. Attorney’s Office for the Southern District of New York and HHS-OIG.\xa0 The claims resolved by this settlement are allegations only; there has been no determination of liability.\xa0 The case is captioned United States ex rel. Moore v. 21st Century Oncology, LLC, No. 2:16-cv-99 (M.D. Fl.).'

In [43]:
df['new_contents'] = df['contents'].apply(preprocess)
df.head()

,id,title,contents,date,topics,components,new_contents
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],U.S. Department Justice U.S. Environmental Pro...
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],131 count criminal indictment unsealed today B...
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...",United States Attorney Office Middle District ...
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],21st Century Oncology LLC agreed pay $ 19.75 m...
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]",21st Century Oncology Inc. certain subsidiarie...

In [45]:
len(df['new_contents'].iloc[4])

4217

# Exercise for Stop words

Exercise1:

* From a Given Text, Count the number of stop words in it.
* Print the percentage of stop word tokens compared to all tokens in a given text.

In [3]:
import spacy 
nlp = spacy.load("en_core_web_sm")

In [7]:
text = '''
Thor: Love and Thunder is a 2022 American superhero film based on Marvel Comics featuring the character Thor, produced by Marvel Studios and 
distributed by Walt Disney Studios Motion Pictures. It is the sequel to Thor: Ragnarok (2017) and the 29th film in the Marvel Cinematic Universe (MCU).
The film is directed by Taika Waititi, who co-wrote the script with Jennifer Kaytin Robinson, and stars Chris Hemsworth as Thor alongside Christian Bale, Tessa Thompson,
Jaimie Alexander, Waititi, Russell Crowe, and Natalie Portman. In the film, Thor attempts to find inner peace, but must return to action and recruit Valkyrie (Thompson),
Korg (Waititi), and Jane Foster (Portman)—who is now the Mighty Thor—to stop Gorr the God Butcher (Bale) from eliminating all gods.
'''

#step1: Create the object 'doc' for the given text using nlp()
doc = nlp(text)

#step2: define the variables to keep track of stopwords count and total words count
stop_word_cnt=0
total_word_count=0

#step3: iterate through all the words in the document
total_word_count = len(doc)
for token in doc:
    if token.is_stop:
        stop_word_cnt+= 1


#step4: print the count of stop words
print(f"The no. of Stop words in the text is : {stop_word_cnt}")
print(f"The no. of Total words in the text is : {total_word_count}")


#step5: print the percentage of stop words compared to total words in the text
print("Percentage of Stop Words in the text is : ",(stop_word_cnt/total_word_count) * 100,"%")

The no. of Stop words in the text is : 40
The no. of Total words in the text is : 160
Percentage of Stop Words in the text is :  25.0 %

Exercise2:

Spacy default implementation considers "not" as a stop word. But in some scenarios removing 'not' will completely change the meaning of the statement/text. For Example, consider these two statements:

- this is a good movie       ----> Positive Statement
- this is not a good movie   ----> Negative Statement
So, after applying stopwords to those 2 texts, both will return "good movie" and does not respect the polarity/sentiments of text.

Now, your task is to remove this stop word "not" in spaCy and help in distinguishing the texts.

Hint: GOOGLE IT! Google is your friend.

In [24]:
from spacy.lang.en.stop_words import STOP_WORDS

In [25]:
# This will NOT work as we need to identify our stop word from the spacy's is_stop.
# print(type(STOP_WORDS)) #  STOP_WORDS is of type set

# if 'not' in STOP_WORDS:
#     STOP_WORDS.remove('not')

# if 'not' in STOP_WORDS:
#     print("Yes Present")
# else:
#     print("Removed")


#Step: remove the stopword 'not' in spacy
nlp.vocab['not'].is_stop = False # We can  done this to remove 'not' from the spacy stop words

In [26]:
# Now we need to distinguish both Texts as Positive/Negative by removing their STOP_WORDS

text1= "this is a good movie"
text2= "this is not a good movie"

def preprocess(text):
    doc= nlp(text)
    no_stop_words = [token.text for token in doc if not token.is_stop]
    return " ".join(no_stop_words)

positive_text = preprocess(text1)
negative_text = preprocess(text2)

print(positive_text)
print(negative_text)

good movie
not good movie

Exercise3:

From a given text, output the most frequently used token after removing all the stop word tokens and punctuations in it.

In [33]:
myText = ''' The India men's national cricket team, also known as Team India or the Men in Blue, represents India in men's international cricket.
It is governed by the Board of Control for Cricket in India (BCCI), and is a Full Member of the International Cricket Council (ICC) with Test,
One Day International (ODI) and Twenty20 International (T20I) status. Cricket was introduced to India by British sailors in the 18th century, and the 
first cricket club was established in 1792. India's national cricket team played its first Test match on 25 June 1932 at Lord's, becoming the sixth team to be
granted test cricket status.
'''


#step1: Create the object 'doc' for the given text using nlp()
#step2: remove all the stop words and punctuations and store all the remaining tokens in a new list

def preprocess_text(text):
    doc = nlp(text)
    no_stop_word_list= [token.text for token in doc if not token.is_stop and not token.is_punct]
    return no_stop_word_list
    

no_stop_word_list= preprocess_text(myText)

#step3: create a new dictionary and get the frequency of words by iterating through the list which contains stored tokens  
frequency_token={}

for token in no_stop_word_list:
    if token != '\n' and token != ' ': #As spacy considers new line and empty spaces as seperate token, it's better to ignore them
        if token not in frequency_token:
            frequency_token[token] = 1
        else:
            frequency_token[token] += 1

print(frequency_token)

#step4: get the maximum frequency word
max_used_token = max(frequency_token.keys(),key=(lambda key: frequency_token[key]))

# Can also do below approach to find most frequent word
# max_freq=0
# for key,value in frequency_token.items():
#     if max_freq < value:
#         max_freq = value
#         max_used_token= key



#step5: finally print the result
print(f"Maximum frequency word is : ",max_used_token)

{'India': 6, 'men': 2, 'national': 2, 'cricket': 5, 'team': 3, 'known': 1, 'Team': 1, 'Men': 1, 'Blue': 1, 'represents': 1, 'international': 1, 'governed': 1, 'Board': 1, 'Control': 1, 'Cricket': 3, 'BCCI': 1, 'Member': 1, 'International': 3, 'Council': 1, 'ICC': 1, 'Test': 2, 'Day': 1, 'ODI': 1, 'Twenty20': 1, 'T20I': 1, 'status': 2, 'introduced': 1, 'British': 1, 'sailors': 1, '18th': 1, 'century': 1, 'club': 1, 'established': 1, '1792': 1, 'played': 1, 'match': 1, '25': 1, 'June': 1, '1932': 1, 'Lord': 1, 'sixth': 1, 'granted': 1, 'test': 1}
Maximum frequency word is :  India