## **NLP Tutorial - Text Representation: TF-IDF**

**What is TF-IDF?**

* TF stands for Term Frequency and denotes the ratio of number of times a particular word appeared in a Document to total number of words in the document.

  **Term Frequency(TF) = [number of times word appeared / total no of words in a document]**

Term Frequency values ranges between 0 and 1. If a word occurs more number of times, then it's value will be close to 1.

* IDF stands for Inverse Document Frequency and denotes the log of ratio of total number of documents/datapoints in the whole dataset to the number of documents that contains the particular word.

   **Inverse Document Frequency(IDF) = [log(Total number of documents / number of documents that contains the word)]**

In IDF, if a word occured in more number of documents and is common across all documents, then it's value will be less and ratio will approaches to 0.

Finally:

   **TF-IDF = Term Frequency(TF) * Inverse Document Frequency(IDF)**

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [ ]:
#let's create the vectorizer and fit the corpus and transform them accordingly
v= TfidfVectorizer()

transformed_output = v.fit_transform(corpus) # Now it will first build the vocabulary and then transform it to out vector representation

print(v.vocabulary_)

{'thor': 25, 'eating': 10, 'pizza': 22, 'loki': 17, 'is': 16, 'ironman': 15, 'ate': 7, 'already': 0, 'apple': 5, 'announcing': 4, 'new': 20, 'iphone': 14, 'tomorrow': 26, 'tesla': 24, 'model': 19, 'google': 12, 'pixel': 21, 'microsoft': 18, 'surface': 23, 'amazon': 2, 'eco': 11, 'dot': 9, 'am': 1, 'biryani': 8, 'and': 3, 'you': 27, 'are': 6, 'grapes': 13}

In [ ]:
# Now let's print the idf score for each of the word present in our vocabulary (dictionary)
all_features_names = v.get_feature_names_out()
print(all_features_names)


for word in all_features_names:
    indx = v.vocabulary_.get(word) # get the index of the word from the vocabulary
    print(f"{word} : {v.idf_[indx]}") # getting the idf score using the v.idf_[indx]

['already' 'am' 'amazon' 'and' 'announcing' 'apple' 'are' 'ate' 'biryani'
 'dot' 'eating' 'eco' 'google' 'grapes' 'iphone' 'ironman' 'is' 'loki'
 'microsoft' 'model' 'new' 'pixel' 'pizza' 'surface' 'tesla' 'thor'
 'tomorrow' 'you']
already : 2.386294361119891
am : 2.386294361119891
amazon : 2.386294361119891
and : 2.386294361119891
announcing : 1.2876820724517808
apple : 2.386294361119891
are : 2.386294361119891
ate : 2.386294361119891
biryani : 2.386294361119891
dot : 2.386294361119891
eating : 1.9808292530117262
eco : 2.386294361119891
google : 2.386294361119891
grapes : 2.386294361119891
iphone : 2.386294361119891
ironman : 2.386294361119891
is : 1.1335313926245225
loki : 2.386294361119891
microsoft : 2.386294361119891
model : 2.386294361119891
new : 1.2876820724517808
pixel : 2.386294361119891
pizza : 2.386294361119891
surface : 2.386294361119891
tesla : 2.386294361119891
thor : 2.386294361119891
tomorrow : 1.2876820724517808
you : 2.386294361119891

**We can see that the word like "is" have low idf score as it is appearing in almost all the docs of the corpus and the words like "thor" "iphone" have higher idf score as they are less common among all the docs**

In [6]:
# Checking out Transformed output that contains Vector representation of each doc of the corpus
print(corpus[:2])
print(transformed_output.toarray()[:2])

['Thor eating pizza, Loki is eating pizza, Ironman ate pizza already', 'Apple is announcing new iphone tomorrow']
[[0.24266547 0.         0.         0.         0.         0.
  0.         0.24266547 0.         0.         0.40286636 0.
  0.         0.         0.         0.24266547 0.11527033 0.24266547
  0.         0.         0.         0.         0.72799642 0.
  0.         0.24266547 0.         0.        ]
 [0.         0.         0.         0.         0.30652086 0.5680354
  0.         0.         0.         0.         0.         0.
  0.         0.         0.5680354  0.         0.26982671 0.
  0.         0.         0.30652086 0.         0.         0.
  0.         0.         0.30652086 0.        ]]

## **E-Commerce Item Catorogy Classification using Tf-Idf**

In [9]:
import pandas as pd

df = pd.read_csv('Ecommerce_data.csv')
print(df.shape)
df.head()

(24000, 2)

                                                Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [ ]:
# Printing the distinct categories of label we have in our dataframe
print(df.label.value_counts())

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

**We have 4 types of categories of label and all are equally Balanced**

In [10]:
# Great now we convert the labels into Numbers as ML model needs numbers
df['label_num'] = df['label'].map({
    'Household' : 0,
    'Books': 1,
    'Electronics': 2,
    'Clothing & Accessories': 3
})

df.head()

                                                Text  ... label_num
0  Urban Ladder Eisner Low Back Study-Office Comp...  ...         0
1  Contrast living Wooden Decorative Box,Painted ...  ...         0
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...  ...         2
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  ...         3
4  Indira Designer Women's Art Mysore Silk Saree ...  ...         3

[5 rows x 3 columns]

In [11]:
# Spliting the data
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    df.Text,
    df.label_num,
    test_size=0.2,
    random_state=2022,
    stratify= df.label_num
)

In [13]:
print(X_train.shape)
print(X_test.shape)

(19200,)
(4800,)

In [16]:
print(y_train.shape)
print(y_train.value_counts())

print(y_test.shape)
print(y_test.value_counts())

(19200,)
label_num
0    4800
2    4800
3    4800
1    4800
Name: count, dtype: int64
(4800,)
label_num
0    1200
2    1200
3    1200
1    1200
Name: count, dtype: int64

### Now we train different models on our data to pick the best one (Without Preprocessing the text)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer

# Firstly trying with KNN
clf = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('knn',KNeighborsClassifier())
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1200
           1       0.97      0.95      0.96      1200
           2       0.97      0.97      0.97      1200
           3       0.97      0.98      0.97      1200

    accuracy                           0.96      4800
   macro avg       0.96      0.96      0.96      4800
weighted avg       0.96      0.96      0.96      4800

In [20]:
# Just checking the first 5 predictions and comparing it with actual predictions
print(y_pred[:5])
print(y_test[:5])

[0 2 3 1 0]
20706    0
19166    2
15209    3
2462     1
6621     3
Name: label_num, dtype: int64

In [ ]:
# Now tring MultinomialNB Classifier
from sklearn.naive_bayes import MultinomialNB

clf = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.96      0.94      1200
           1       0.98      0.92      0.95      1200
           2       0.97      0.97      0.97      1200
           3       0.97      0.99      0.98      1200

    accuracy                           0.96      4800
   macro avg       0.96      0.96      0.96      4800
weighted avg       0.96      0.96      0.96      4800

In [ ]:
# Now RandomForest Classifier
from sklearn.ensemble import RandomForestClassifier

clf = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('randomForest',RandomForestClassifier())
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred)) # Giving Slightly Good performance from others (till now)

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1200
           1       0.97      0.98      0.98      1200
           2       0.98      0.97      0.97      1200
           3       0.98      0.99      0.98      1200

    accuracy                           0.97      4800
   macro avg       0.97      0.97      0.97      4800
weighted avg       0.97      0.97      0.97      4800

### Now By doing preprocessing we Again check the results for all models

In [32]:

import spacy

nlp = spacy.load("en_core_web_sm")

def preprocess(text): # It will remove the stop words and punctuations and also Lemmatize the text.
    doc = nlp(text)
    preprocess_text=[ token.lemma_ for token in doc if not token.is_stop and not token.is_punct ]
    return " ".join(preprocess_text)

In [33]:
df['preprocessed_text'] = df['Text'].apply(preprocess)
df.head()

                                                Text  ...                                  preprocessed_text
0  Urban Ladder Eisner Low Back Study-Office Comp...  ...  Urban Ladder Eisner Low Study Office Computer ...
1  Contrast living Wooden Decorative Box,Painted ...  ...  contrast live Wooden Decorative Box Painted Bo...
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...  ...  IO Crest SY PCI40010 PCI RAID Host Controller ...
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  ...  ISAKAA Baby Socks bear 8 Years- Pack 4 6 8 12 ...
4  Indira Designer Women's Art Mysore Silk Saree ...  ...  Indira Designer woman Art Mysore Silk Saree Bl...

[5 rows x 4 columns]

In [34]:
# Again spliting the data but this time with the Preprocessed_Text
X_train,X_test,y_train,y_test = train_test_split(
    df.preprocessed_text,
    df.label_num,
    test_size=0.2,
    random_state= 2022,
    stratify= df.label_num
)

In [35]:
# KNN
clf = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('knn',KNeighborsClassifier())
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1200
           1       0.97      0.95      0.96      1200
           2       0.97      0.97      0.97      1200
           3       0.97      0.98      0.98      1200

    accuracy                           0.96      4800
   macro avg       0.96      0.96      0.96      4800
weighted avg       0.96      0.96      0.96      4800

In [36]:
# MultinomialNB
clf = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.96      0.94      1200
           1       0.98      0.92      0.95      1200
           2       0.96      0.97      0.96      1200
           3       0.97      0.99      0.98      1200

    accuracy                           0.96      4800
   macro avg       0.96      0.96      0.96      4800
weighted avg       0.96      0.96      0.96      4800

In [37]:
# Randomforest
clf = Pipeline([
    ('tfidf',TfidfVectorizer()),
    ('randomForest',RandomForestClassifier())
])

clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1200
           1       0.98      0.98      0.98      1200
           2       0.98      0.97      0.98      1200
           3       0.98      0.99      0.99      1200

    accuracy                           0.98      4800
   macro avg       0.98      0.98      0.98      4800
weighted avg       0.98      0.98      0.98      4800

### **We can see that after Preprocessing the accuracy is improved slightly**